{
    "error": "HTTPSConnectionPool(host='ccp.cloudera.com', port=443): Max retries exceeded with url: /display/DOC/Cloudera+Security+Bulletin (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')])\")))"
}