{
    "error": "HTTPSConnectionPool(host='dev.icinga.org', port=443): Max retries exceeded with url: /issues/3532 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d3ab3880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
}