{
    "error": "HTTPConnectionPool(host='216.188.41.136', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7effc5bb27f0>, 'Connection to 216.188.41.136 timed out. (connect timeout=10)'))"
}