{
    "uvi": [
        {
            "extracted_data": {
                "advisory_id": "DSA-2340-1",
                "advisory_type": "DSA",
                "affected": [
                    {
                        "distribution_affected": "lenny",
                        "fixed in": "For the oldstable distribution (lenny), this problem has been fixed in postgresql-8.3 version 8.3.16-0lenny1"
                    },
                    {
                        "distribution_affected": "squeeze",
                        "fixed in": "For the stable distribution (squeeze), this problem has been fixed in postgresql-8.4 version 8.4.9-0squeeze1"
                    },
                    {
                        "distribution_affected": "wheezy) and unstable distribution (sid",
                        "fixed in": "For the testing distribution (wheezy) and unstable distribution (sid), this problem has been fixed in postgresql-8.4 version 8.4.9-1, postgresql-9.0 9.0.5-1 and postgresql-9.1 9.1~rc1-1"
                    }
                ],
                "cve_ids": [
                    "CVE-2011-2483"
                ],
                "info_date_string": "2011-11-07",
                "package_name": "postgresql-8.3, postgresql-8.4, postgresql-9.0",
                "product_name": "Linux",
                "vendor_name": "Debian",
                "vulnerability_status": "yes"
            },
            "meta_data": {
                "uvi_processed_timestamp": "2021-08-03T02:08:25.163735Z",
                "uvi_script_hash": "4d6742cc7fd27472fb19a4c307967e9bd4eebb55e7fcb78430305de2fcc0321848e49403978a5fd94a243249bc017da3919fa53cab26676c5c6b91ab2d5478d4",
                "uvi_script_name": "./www.debian.org-processing.py",
                "uvi_script_version": "0.1.2",
                "uvi_url_processed": "https://www.debian.org/security/2011/dsa-2340"
            }
        }
    ]
}