{
    "error": "HTTPSConnectionPool(host='blog.quake.so', port=443): Max retries exceeded with url: /post/zeroshell_linux_router_rce/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52daf09790>, 'Connection to blog.quake.so timed out. (connect timeout=10)'))"
}