{
    "error": "HTTPSConnectionPool(host='embedi.org', port=443): Max retries exceeded with url: /blog/remotely-compromise-devices-by-using-bugs-in-marvell-avastar-wi-fi-from-zero-knowledge-to-zero-click-rce/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d3a95190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
}