{
    "error": "HTTPSConnectionPool(host='dev.alternc.org', port=443): Max retries exceeded with url: /trac/alternc/milestone/0.9.6 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d3b49970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}