{
    "error": "HTTPSConnectionPool(host='blog.redactedsec.net', port=443): Max retries exceeded with url: /exploits/2018/04/26/nagios.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52dae8e940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}