
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>
Issue 32056: Improve exceptions in aifc, sunau and wave - Python tracker

</title>
<link rel="shortcut icon" href="@@file/favicon.ico" />
<link rel="stylesheet" type="text/css" href="@@file/main.css" />
<link rel="stylesheet" type="text/css" href="@@file/style.css" />
<link rel="search" type="application/opensearchdescription+xml" href="@@file/osd.xml" title="Python bug tracker search" />
<meta http-equiv="Content-Type"
      content="text/html; charset=utf-8" />

<script nonce="b3a264cb7dd6e5b33c1da51a4e77b33f637d759d89f30b6cce3767ca4a1211cb" type="text/javascript">
submitted = false;
function submit_once() {
    if (submitted) {
        alert("Your request is being processed.\nPlease be patient.");
        return false;
    }
    submitted = true;
    return true;
}

function help_window(helpurl, width, height) {
    HelpWin = window.open('https://bugs.python.org/' + helpurl, 'RoundupHelpWindow', 'scrollbars=yes,resizable=yes,toolbar=no,height='+height+',width='+width);
    HelpWin.focus ()
}
</script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/jquery-ui.js"></script>
<script type="text/javascript" src="@@file/issue.item.js"></script>
<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" />


</head>
<body>
  <!--  Logo  -->
  <h1 id="logoheader">
    <a accesskey="1" href="." id="logolink">
       <img src="@@file/python-logo.gif" alt="homepage" border="0" id="logo" /></a>
  </h1>

<div id="utility-menu">
<!-- Search Box -->
<div id="searchbox">
    <form name="searchform" method="get" action="issue" id="searchform">
      <div id="search">
       <input type="hidden" name="@columns"
              value="id,activity,title,creator,assignee,status,type" />
       <input type="hidden" name="@sort" value="-activity" />
       <input type="hidden" name="@filter" value="status" />
       <input type="hidden" name="@action" value="searchid" />
       <input type="hidden" name="ignore" value="file:content" />
       <input class="input-text" id="search-text"
              name="@search_text" size="10" />
       <input type="submit" id="submit" value="search" name="submit" class="input-button" />
       <input type="radio" name="status"
              id="status_notresolved" value="-1,1,3" />
       <label for="status_notresolved">open</label>
       <input type="radio" name="status" checked="checked"
              id="status_all" value="-1,1,2,3" />
       <label for="status_all">all</label>
      </div>
     </form>
</div>
</div>


<div id="left-hand-navigation">
<!--  Main Menu NEED LEVEL TWO HEADER AND FOOTER -->
<div id="menu">
  <ul class="level-one">
    <li><a href="https://www.python.org/" title="Go to the Python homepage">Python Home</a></li>
    <li><a href="https://www.python.org/about/" title="About The Python Language">About</a></li>
    <li><a href="https://www.python.org/blogs/" title="">News</a></li>
    <li><a href="https://www.python.org/doc/" title="">Documentation</a></li>
    <li><a href="https://www.python.org/downloads/" title="">Downloads</a></li>
    <li><a href="https://www.python.org/community/" title="">Community</a></li>
    <li><a href="https://www.python.org/psf/" title="Python Software Foundation">Foundation</a></li>
    <li><a href="https://devguide.python.org/" title="Python Developer's Guide">Developer's Guide</a></li>
    <li class="selected"><a href="." class="selected" title="Python Issue Tracker">Issue Tracker</a>
      <ul class="level-two">
        <li>
          <strong>Issues</strong>
          <ul class="level-three">
            
            <li><a href="issue?@template=search&amp;status=1">Search</a></li>
            <li><a href="issue?@action=random">Random Issue</a></li>
            <li>
              <form method="post" action="issue32056">
                <input type="submit" class="form-small"
                       value="Show issue:" />
                <input class="form-small" size="4" type="text" name="@number" />
                <input type="hidden" name="@type" value="issue" />
                <input type="hidden" name="@action" value="show" />
              </form>
            </li>
          </ul>
        </li>


        <li>
          <strong>Summaries</strong>
          <ul class="level-three">
            

            

            

            <li>
              <a href="issue?status=1&amp;@sort=-activity&amp;@columns=id%2Cactivity%2Ctitle%2Ccreator%2Cstatus&amp;@dispname=Issues%20with%20patch&amp;@startwith=0&amp;@group=priority&amp;keywords=2&amp;@action=search&amp;@filter=&amp;@pagesize=50">Issues with patch</a>
            </li>

            <li>
              <a href="issue?status=1&amp;@sort=-activity&amp;@columns=id%2Cactivity%2Ctitle%2Ccreator%2Cstatus&amp;@dispname=Easy%20issues&amp;@startwith=0&amp;@group=priority&amp;keywords=6&amp;@action=search&amp;@filter=&amp;@pagesize=50">Easy issues</a>
            </li>

            <li>
              <a href="issue?@template=stats">Stats</a>
            </li>

          </ul>
        </li>


        <li>
          <strong>User</strong>
          <form method="post" action="issue32056">
          <ul class="level-three">
            <li>
                Login&nbsp;(OpenID&nbsp;possible)<br />
	         <a style="display:inline;width:0;margin:0"
             href="issue32056?@action=oic_login&amp;provider=Google">
                  <img hspace="0" vspace="0" width="16"
                       height="16"
                       src="https://www.google.com/favicon.ico"
                       alt="Google" title="Google" /></a>
	         <a style="display:inline;width:0;margin:0"
             href="issue32056?@action=oic_login&amp;provider=GitHub">
                  <img hspace="0" vspace="0" width="16"
                       height="16"
                       src="https://www.github.com/favicon.ico"
                       alt="GitHub" title="GitHub" /></a>
	         <a style="display:inline;width:0;margin:0"
             href="issue32056?@action=openid_login&amp;provider=Launchpad">
                  <img hspace="0" vspace="0" width="16"
                       height="16"
                       src="https://launchpad.net/favicon.ico"
                       alt="Launchpad" title="Launchpad" /></a>
                <input size="10" name="openid_identifier" style="background:url(@@file/openid-16x16.gif)
                  center left no-repeat;padding-left:16px" /><br />
                <input size="10" type="password" name="__login_password" /><br />
                <input type="hidden" name="@action" value="Login" />
                <input type="checkbox" name="remember" id="remember" />
                <label for="remember">Remember me?</label><br />
                <input class="form-small" type="submit"
                       value="Login" /><br />
                <input type="hidden" name="__came_from"
                       value="https://bugs.python.org/issue32056?">
                
                <input type="hidden" name="@sort" value=""/>
<input type="hidden" name="@group" value=""/>
<input type="hidden" name="@pagesize" value="50"/>
<input type="hidden" name="@startwith" value="0"/>
            </li>
            <li>
                <a href="user?@template=register">Register</a>
            </li>
            <li><a href="user?@template=forgotten">Lost&nbsp;your&nbsp;login?</a></li>
          </ul>
          </form>
        </li>

        

        

        <li>
          <strong>Administration</strong>
          <ul class="level-three">
            
            <li>
                <a href="user?@sort=username">User List</a></li>
            <li>
                <a href="user?iscommitter=1&amp;@action=search&amp;@sort=username&amp;@pagesize=300">Committer List</a></li>
            
            
            
          </ul>
        </li>

        <li>
          <strong>Help</strong>
          <ul class="level-three">
            <li><a href="http://docs.python.org/devguide/triaging.html">
                Tracker Documentation</a></li>
            <li><a href="http://wiki.python.org/moin/TrackerDevelopment">
                Tracker Development</a></li>
            <li><a href="https://github.com/python/psf-infra-meta/issues">
                Report Tracker Problem</a></li>
          </ul>
        </li>

      </ul>
    </li>
  </ul>
</div> <!-- menu -->
</div> <!-- left-hand-navigation -->

<div id="content-body">
<div id="body-main">
<div id="content">
<div id="breadcrumb">
 
 
 Issue32056
 
</div>
 
 





<div>

<form method="post" name="itemSynopsis"
      onsubmit="return submit_once()"
      enctype="multipart/form-data" action="issue32056">

<fieldset><legend>classification</legend>
<table class="form">
<tr>
 <th class="required"><a href="http://docs.python.org/devguide/triaging.html#title" target="_blank">Title</a>:</th>
 
 <td colspan="3">
  <span>Improve exceptions in aifc, sunau and wave</span>
  <input type="hidden" name="title"
         value="Improve exceptions in aifc, sunau and wave">
 </td>
</tr>

<tr>
 <th class="required"><a href="http://docs.python.org/devguide/triaging.html#type" target="_blank">Type</a>:</th>
 <td>enhancement</td>
 <th><a href="http://docs.python.org/devguide/triaging.html#stage" target="_blank">Stage</a>:</th>
 <td>resolved</td>
</tr>

<tr>
 <th><a href="http://docs.python.org/devguide/triaging.html#components" target="_blank">Components</a>:</th>
 <td>Library (Lib)</td>
 <th><a href="http://docs.python.org/devguide/triaging.html#versions" target="_blank">Versions</a>:</th>
 <td>Python 3.8, Python 3.7</td>
</tr>
</table>
</fieldset>

<fieldset><legend>process</legend>
<table class="form">
<tr>
  <th><a href="http://docs.python.org/devguide/triaging.html#status" target="_blank">Status</a>:</th>
  <td>closed</td>
  <th><a href="http://docs.python.org/devguide/triaging.html#resolution" target="_blank">Resolution</a>:</th>
  <td>fixed</td>
</tr>

<tr>
 <th>
    <a href="http://docs.python.org/devguide/triaging.html#dependencies"
       target="_blank">Dependencies</a>:
 </th>
 <td>
  
  
 </td>
 <th><a href="http://docs.python.org/devguide/triaging.html#superseder" target="_blank">Superseder</a>:</th>
 <td>
  
 
 </td>
 </tr>
 <tr>
 <th>
   <a href="http://docs.python.org/devguide/triaging.html#assigned-to"
      target="_blank">Assigned To</a>:
 </th>
 
 <td>
  
 </td>
 <th>
   <a href="http://docs.python.org/devguide/triaging.html#nosy-list"
      target="_blank">Nosy List</a><!--
        <span tal:condition="context/nosy_count" tal:replace="python: ' (%d)' % context.nosy_count" /> -->:
 </th>
 <td>
     BT123, miss-islington, ned.deily, serhiy.storchaka
     
 </td>
</tr>
<tr>
 <th>
   <a href="http://docs.python.org/devguide/triaging.html#priority"
      target="_blank">Priority</a>:
 </th>
 <td>normal</td>
 <th>
    <a href="http://docs.python.org/devguide/triaging.html#keywords"
       target="_blank">Keywords</a>:
 </th>
 <td>patch</td>


</tr>









</table>
</fieldset>

</form>

<p>Created on <strong>2017-11-17 09:42</strong> by <strong>BT123</strong>, last changed <strong>2018-03-18 20:52</strong> by <strong>serhiy.storchaka</strong>. This issue is now <strong style="color:#00F; background-color:inherit;">closed</strong>.</p>

<table class="files">
 <tr><th colspan="5" class="header">Files</th></tr>
 <tr>
  <th>File name</th>
  <th>Uploaded</th>
  <th>Description</th>
  <th>Edit</th>
 </tr>
 <tr>
  <td>
   <a href="file47270/audio-testcase.wav">audio-testcase.wav</a>
  </td>
  <td>
   <span>BT123</span>,
   <span>2017-11-17 09:42</span>
  </td>
  <td>open the audio file using wave.open function and will lead to divided by zero</td>
  <td>
      
      
      
  </td>
 </tr>
</table>

<table class="files">
 <tr><th class="header" colspan="4">Pull Requests</th></tr>
 <tr>
  <th>URL</th>
  <th>Status</th>
  <th>Linked</th>
  <th>Edit</th>
 </tr>
 <tr>
  <td><a href="https://github.com/python/cpython/pull/4437" title="">PR 4437</a></td>
  <td></td>
  <td>
   <span>BT123</span>,
   <span>2017-11-17 09:42</span>
  </td>
  <td>
    
  </td>
 </tr>
 <tr>
  <td><a href="https://github.com/python/cpython/pull/4440" title="bpo-32056: Add check for channels of wav file in wave module">PR 4440</a></td>
  <td>closed</td>
  <td>
   <span>BT123</span>,
   <span>2017-11-17 10:00</span>
  </td>
  <td>
    
  </td>
 </tr>
 <tr>
  <td><a href="https://github.com/python/cpython/pull/5951" title="bpo-32056: Improve exceptions in aifc, wave and sunau.">PR 5951</a></td>
  <td>merged</td>
  <td>
   <span>serhiy.storchaka</span>,
   <span>2018-03-01 15:52</span>
  </td>
  <td>
    
  </td>
 </tr>
 <tr>
  <td><a href="https://github.com/python/cpython/pull/6139" title="[3.7] bpo-32056: Improve exceptions in aifc, wave and sunau. (GH-5951)">PR 6139</a></td>
  <td>merged</td>
  <td>
   <span>miss-islington</span>,
   <span>2018-03-18 09:01</span>
  </td>
  <td>
    
  </td>
 </tr>
</table>





<table class="messages">
 <tr><th colspan="4" class="header">Messages (15)</th></tr>
 
  <tr>
    <th>
     <a href="#msg306420" id="msg306420">msg306420</a> - <a
    href="msg306420">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2017-11-17 09:42</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>I found a bug in wave.py because there is no check for self._channel in _read_fmt_chunk function.
When I try to open a wav file which channel is zero, it will crash bacause of divided by zero in initfp function.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313079" id="msg313079">msg313079</a> - <a
    href="msg313079">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2018-03-01 02:25</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>the bug still in the Python 3.7.0b2 - 2018-02-28</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313080" id="msg313080">msg313080</a> - <a
    href="msg313080">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2018-03-01 02:52</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>The CVE email:
The CVE ID is below. Please check whether the vulnerability still
exists in Python 3.6.4, and please inform the software maintainer that
the CVE ID has been assigned: <a href="https://bugs.python.org">https://bugs.python.org</a>

Use CVE-2017-18207 for this vulnerability in Python.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313084" id="msg313084">msg313084</a> - <a
    href="msg313084">(view)</a></th>
   <th>Author: Serhiy Storchaka (serhiy.storchaka) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-01 06:10</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>I have no idea why this was classified as a vulnerability. I don't think it can crash an application. If you have an example of crashing please provide it.

I would not classify this issue even as a bug. It is obvious that invalid files can cause an exception. It may be good to detect some of errors earlier and raise more specific exception (Error would be more appropriate here than ValueError). But in general validating the wave file is not the purpose of this module, and this task can't be performed without reading the whole file, not only the header.

All changes in wave.py should be ported to aifc.py and sunau.py and needs tests.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313087" id="msg313087">msg313087</a> - <a
    href="msg313087">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2018-03-01 09:37</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>ok, I found this bug when I use librosa-0.5.1 to read audio file in the audio-classification project -- an ASR project. (<a href="https://github.com/nextco/audio-classification">https://github.com/nextco/audio-classification</a>)

In the project, librosa.load function read audio file, and it called wave.open function finally. But all of the functions don't validate the audio file which lead to the project dividing by zero. 

Although the bug is easy and small, I think the bug should be fixed because there are so many python-library(such as librosa, audioread) use it without validation in more and more popular ASR project.

My program backtrace is as follow:
<a href="https://github.com/BT123/testcasesForMyRequest/blob/master/wave-1.png">https://github.com/BT123/testcasesForMyRequest/blob/master/wave-1.png</a>
<a href="https://github.com/BT123/testcasesForMyRequest/blob/master/wave-2.png">https://github.com/BT123/testcasesForMyRequest/blob/master/wave-2.png</a></pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313097" id="msg313097">msg313097</a> - <a
    href="msg313097">(view)</a></th>
   <th>Author: Serhiy Storchaka (serhiy.storchaka) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-01 16:00</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre><a href="https://github.com/python/cpython/pull/5951" class="open" title="GitHub PR 5951: [open] bpo-44062: Fix PYTHON_FOR_BUILD interpreter lookup for cross-compile …">PR 5951</a> adds explicit checks for the number of channels and sample width when read audio files in aifc, sunau and wave and converts some struct.error to EOFError when the file is truncated in wave.

This change can break an existing code that currently successfully opens corrupted audio files and read only headers, but not audio samples. Therefore it is safer to not backport it, even if classify this issue as a bug.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313111" id="msg313111">msg313111</a> - <a
    href="msg313111">(view)</a></th>
   <th>Author: Ned Deily (ned.deily) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-01 21:13</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>@zhangdeyue, can you please request that the CVE be unassigned?  I think we all agree this is *not* a security issue.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313121" id="msg313121">msg313121</a> - <a
    href="msg313121">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2018-03-02 02:20</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>I agree that it is very small, but I still think it is indeed a security issue, because it can crash real world program when called by some library used in Deep Learning ASR project. 

Does a CVE assigned have any negative impact on you?</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313123" id="msg313123">msg313123</a> - <a
    href="msg313123">(view)</a></th>
   <th>Author: Ned Deily (ned.deily) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-02 03:43</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>&gt; I agree that it is very small, but I still think it is indeed a security issue, because it can crash real world program when called by some library used in Deep Learning ASR project. 

That sounds like a programming error, not a security bug.  The case you describe causes a Python exception to be raised.  As noted in the Python Language Reference: "Exceptions are a means of breaking out of the normal flow of control of a code block in order to handle errors or other exceptional conditions."  Any program using Python libraries needs to be prepared to handle a wide variety of exception, particularly if the program is dealing with external data, like an arbitrary audio file.  If a program is failing because it fails to properly check for exceptions, like by using a "try" block, that's a bug in the program, not a security problem in Python.

&gt; Does a CVE assigned have any negative impact on you?

Yes, because it implies that there is some security problem in Python that downstream vendors and users need to be concerned about and should expect some fix or other mediation from the responsible project.  That is not the case here.

Now, as Serhily noted, it might be nice if the exception produced a more meaningful message but changing that would not change the end result for a program: it will still see an exception and either need to handle it or be terminated like with any other Python exception.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313125" id="msg313125">msg313125</a> - <a
    href="msg313125">(view)</a></th>
   <th>Author: zhangdeyue (BT123) <span title="Contributor form received">*</span></th>
   <th>Date: 2018-03-02 04:14</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>I'm confused now. For any program which receive external file, to check the input file is necessary to do, isn't it? And program error lead to security bug, that's not right? 

The program itself check input file, catch and show some exceptions or asserts means that the error has been taken into account and the program is robust. 

However, I got the message from the system's check.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg313230" id="msg313230">msg313230</a> - <a
    href="msg313230">(view)</a></th>
   <th>Author: Ned Deily (ned.deily) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-04 23:43</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>&gt; For any program which receive external file, to check the input file is necessary to do, isn't it?

Yes and no.  wave.py is doing checking and can raise various exceptions.  So a well-designed program has to be prepared to handle exceptions when calling wave.py.  The suggested fix would provide a more specific error message and exception, rather than a division by zero one, but the net effect to the caller of wave.py is the same.

&gt; And program error lead to security bug, that's not right?

No. Just because a program can terminate due to an uncaught exception is not by itself considered a security error.  See <a href="https://www.python.org/news/security/">https://www.python.org/news/security/</a> for a discussion. In particular, "The general rule is any attack worth reporting via the security address must allow an attacker to affect the confidentiality, integrity and availability of the Python application or its system for which the attacker does not already have the capability."  As things stand now, if an application is vulnerable to a denial-of-service attack due to a faulty wav file, it is a failure in that application to be handling possible exceptions from wave.py, not a security issue in Python itself.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg314030" id="msg314030">msg314030</a> - <a
    href="msg314030">(view)</a></th>
   <th>Author: Serhiy Storchaka (serhiy.storchaka) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-18 07:55</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>
New changeset <a href="https://hg.python.org/lookup/134cb01cda50f02725575808130b05d2d776693f">134cb01cda50f02725575808130b05d2d776693f</a> by Serhiy Storchaka in branch 'master':
<a class="closed" title="[closed] Improve exceptions in aifc, sunau and wave" href="issue32056">bpo-32056</a>: Improve exceptions in aifc, wave and sunau. (<a href="https://github.com/python/cpython/pull/5951" class="open" title="GitHub PR 5951: [open] bpo-44062: Fix PYTHON_FOR_BUILD interpreter lookup for cross-compile …">GH-5951</a>)
<a href="https://github.com/python/cpython/commit/134cb01cda50f02725575808130b05d2d776693f">https://github.com/python/cpython/commit/134cb01cda50f02725575808130b05d2d776693f</a>
</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg314033" id="msg314033">msg314033</a> - <a
    href="msg314033">(view)</a></th>
   <th>Author: Serhiy Storchaka (serhiy.storchaka) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-18 09:16</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>Now open() in modules aifc, sunau and wave will raise only EOFError (if the file was truncated) or corresponding module error exception on corrupted files. aifc.open() can raise also OverflowError, but this is a different <a class="open" title="[open] Issues with reading large float values in AIFC files" href="issue32978">issue32978</a>. And of course OSError, MemoryError, RecursionError and KeyboardInterrupt can be raised for causes not related to the correctness of the file.

I withdraw the part of my claim in <a href="msg313084">msg313084</a>. I have tested -- backporting this is safe, because some error always was raised in open(). But it can help existing user code which was not aware about wider set of exceptions (like in the original report). It can work in common case, and handle most corrupted files well, but fail in cases of specially created malicious data. Thus I think it is worth to backport this change at least to 3.7. What are your thoughts Ned?</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg314055" id="msg314055">msg314055</a> - <a
    href="msg314055">(view)</a></th>
   <th>Author: Ned Deily (ned.deily) <span title="Contributor form received">*</span> <img src="@@file/committer.png" title="Python committer" alt="(Python committer)" /></th>
   <th>Date: 2018-03-18 20:41</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>I'm OK with merging this for 3.7.0b3.</pre>
   </td>
  </tr>
 
 
  <tr>
    <th>
     <a href="#msg314057" id="msg314057">msg314057</a> - <a
    href="msg314057">(view)</a></th>
   <th>Author: miss-islington (miss-islington)</th>
   <th>Date: 2018-03-18 20:50</th>
  </tr>
  <tr>
   <td colspan="4" class="content">
    
    <pre>
New changeset <a href="https://hg.python.org/lookup/3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371">3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371</a> by Miss Islington (bot) in branch '3.7':
<a class="closed" title="[closed] Improve exceptions in aifc, sunau and wave" href="issue32056">bpo-32056</a>: Improve exceptions in aifc, wave and sunau. (<a href="https://github.com/python/cpython/pull/5951" class="open" title="GitHub PR 5951: [open] bpo-44062: Fix PYTHON_FOR_BUILD interpreter lookup for cross-compile …">GH-5951</a>)
<a href="https://github.com/python/cpython/commit/3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371">https://github.com/python/cpython/commit/3c0a5a7c7ba8fbbc95dd1fe76cd7a1c0ce167371</a>
</pre>
   </td>
  </tr>
 
</table>

<table class="history table table-condensed table-striped"><tr><th colspan="4" class="header">
History
</th></tr><tr>
<th>Date</th>
<th>User</th>
<th>Action</th>
<th>Args</th>
</tr>
<tr><td>2018-03-18&nbsp;20:52:01</td><td>serhiy.storchaka</td><td>set</td><td>status: open -> closed<br />resolution: fixed<br />stage: patch review -> resolved</td></tr>
<tr><td>2018-03-18&nbsp;20:50:43</td><td>miss-islington</td><td>set</td><td>nosy:
  + <a rel="nofollow" href="user27838">miss-islington</a><br />messages:
  + <a rel="nofollow" href="msg314057">msg314057</a><br /></td></tr>
<tr><td>2018-03-18&nbsp;20:41:00</td><td>ned.deily</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg314055">msg314055</a><br />versions:
  + Python 3.7</td></tr>
<tr><td>2018-03-18&nbsp;09:16:54</td><td>serhiy.storchaka</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg314033">msg314033</a></td></tr>
<tr><td>2018-03-18&nbsp;09:01:20</td><td>miss-islington</td><td>set</td><td>pull_requests:
  + <a rel="nofollow" href="pull_request5896">pull_request5896</a></td></tr>
<tr><td>2018-03-18&nbsp;07:55:56</td><td>serhiy.storchaka</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg314030">msg314030</a></td></tr>
<tr><td>2018-03-04&nbsp;23:43:55</td><td>ned.deily</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313230">msg313230</a></td></tr>
<tr><td>2018-03-02&nbsp;04:14:47</td><td>BT123</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313125">msg313125</a></td></tr>
<tr><td>2018-03-02&nbsp;03:43:44</td><td>ned.deily</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313123">msg313123</a></td></tr>
<tr><td>2018-03-02&nbsp;02:20:02</td><td>BT123</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313121">msg313121</a></td></tr>
<tr><td>2018-03-01&nbsp;21:13:07</td><td>ned.deily</td><td>set</td><td>keywords:
  - <a rel="nofollow" href="keyword15">security_issue</a><br />nosy:
  + <a rel="nofollow" href="user5248">ned.deily</a><br />messages:
  + <a rel="nofollow" href="msg313111">msg313111</a><br /><br /></td></tr>
<tr><td>2018-03-01&nbsp;16:00:55</td><td>serhiy.storchaka</td><td>set</td><td>title: Improve exceptions in Lib/wave.py -> Improve exceptions in aifc, sunau and wave<br />messages:
  + <a rel="nofollow" href="msg313097">msg313097</a><br />versions:
  + Python 3.8</td></tr>
<tr><td>2018-03-01&nbsp;15:52:24</td><td>serhiy.storchaka</td><td>set</td><td>keywords:
  + <a rel="nofollow" href="keyword2">patch</a><br />pull_requests:
  + <a rel="nofollow" href="pull_request5717">pull_request5717</a></td></tr>
<tr><td>2018-03-01&nbsp;09:37:53</td><td>BT123</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313087">msg313087</a><br />versions:
  - Python 3.8</td></tr>
<tr><td>2018-03-01&nbsp;06:10:13</td><td>serhiy.storchaka</td><td>set</td><td>type: crash -> enhancement<br />title: bug in Lib/wave.py -> Improve exceptions in Lib/wave.py<br />messages:
  + <a rel="nofollow" href="msg313084">msg313084</a><br />versions:
  + Python 3.8, - Python 3.7</td></tr>
<tr><td>2018-03-01&nbsp;02:55:16</td><td>ned.deily</td><td>set</td><td>keywords:
  + <a rel="nofollow" href="keyword15">security_issue</a>, - <a rel="nofollow" href="keyword2">patch</a><br />nosy:
  + <a rel="nofollow" href="user15623">serhiy.storchaka</a><br /></td></tr>
<tr><td>2018-03-01&nbsp;02:52:52</td><td>BT123</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313080">msg313080</a></td></tr>
<tr><td>2018-03-01&nbsp;02:25:46</td><td>BT123</td><td>set</td><td>messages:
  + <a rel="nofollow" href="msg313079">msg313079</a><br />versions:
  + Python 3.7, - Python 3.6</td></tr>
<tr><td>2017-11-17&nbsp;10:00:14</td><td>BT123</td><td>set</td><td>keywords:
  + <a rel="nofollow" href="keyword2">patch</a><br />stage: patch review<br />pull_requests:
  + <a rel="nofollow" href="pull_request4382">pull_request4382</a></td></tr>
<tr><td>2017-11-17&nbsp;09:42:26</td><td>BT123</td><td>create</td><td></td></tr>
</table>

</div>


</div> <!-- content-body -->
<div id="footer">
<div id="credits">
  Hosted on <a href="https://m.do.co/c/783434964889" title="Hosted on DigitalOcean">DigitalOcean</a>,
  <br>
  Supported by <a href="https://python.org/psf-landing/" title="The Python Software Foundation">The Python Software Foundation</a>,
  <br>
  Powered by <a href="http://roundup.sourceforge.net" title="Powered by the Roundup Issue Tracker">Roundup</a>
</div> <!-- credits -->
Copyright &copy; 1990-2020, <a href="http://python.org/psf">Python Software Foundation</a><br />
<a href="http://python.org/about/legal">Legal Statements</a>
</div> <!-- footer -->
</div> <!-- body-main -->
</div> <!-- content -->



</body>
</html>

