{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2020-02-19",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2020/dsa-4629"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-4629-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2020-7471"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "stretch",
                    "fixed in": "1:1.10.7-2+deb9u8"
                },
                {
                    "distribution_affected": "buster",
                    "fixed in": "1:1.11.28-1~deb10u1"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:09:20.041535Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}