{
    "error": "HTTPConnectionPool(host='alioth.debian.org', port=80): Max retries exceeded with url: /frs/shownotes.php?release_id=1019 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effc5b4a940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
}