{
    "error": "HTTPSConnectionPool(host='deadb0x.io', port=443): Max retries exceeded with url: /lunchb0x/cve-2020-24572/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01d409b400>, 'Connection to deadb0x.io timed out. (connect timeout=10)'))"
}