{
    "uvi": [
        {
            "extracted_data": {
                "advisory_id": "DSA-4699-1",
                "advisory_type": "DSA",
                "affected": [
                    {
                        "distribution_affected": "buster), these problems have been fixed in version 4.19.118-2+deb10u1. This version also fixes some related bugs that do not have their own CVE IDs, and a regression in the &lt;linux/swab.h&gt; UAPI header introduced in the previous point release (bug #960271",
                        "fixed in": "4.19.118-2+deb10u1. This version also fixes some related bugs that do not have their own CVE IDs, and a regression in the &lt;linux/swab.h&gt; UAPI header introduced in the previous point release (bug #960271)"
                    }
                ],
                "cve_ids": [
                    "CVE-2020-12768",
                    "CVE-2020-0543",
                    "CVE-2019-3016",
                    "CVE-2020-12770",
                    "CVE-2020-10711",
                    "CVE-2020-13143",
                    "CVE-2020-12114",
                    "CVE-2019-19462",
                    "CVE-2020-10757",
                    "CVE-2020-12464",
                    "CVE-2020-10732",
                    "CVE-2020-10751"
                ],
                "info_date_string": "2020-06-09",
                "package_name": "linux",
                "product_name": "Linux",
                "vendor_name": "Debian",
                "vulnerability_status": "yes"
            },
            "meta_data": {
                "uvi_processed_timestamp": "2021-08-03T00:33:33.850033Z",
                "uvi_script_hash": "20bfa52174710e3ef03e692906bf13d6dba83a2e3b692e3af64bcaa4baf9adefee00eda3bd26a54bba72b98d28392aed0e91a28cf4b5b6057084ba6ef34d3d4b",
                "uvi_script_name": "./www.debian.org-processing.py",
                "uvi_script_version": "0.1.1",
                "uvi_url_processed": "https://www.debian.org/security/2020/dsa-4699"
            }
        }
    ]
}