{
    "osv": {
        "package": {
            "name": "python-django"
        },
        "published": "2015-11-25",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2015/dsa-3404"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-3404-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2015-8213"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "wheezy",
                    "fixed in": "1.4.5-1+deb7u14"
                },
                {
                    "distribution_affected": "jessie",
                    "fixed in": "1.7.7-1+deb8u3"
                },
                {
                    "distribution_affected": "sid",
                    "fixed in": "1.8.7-1"
                }
            ],
            "package_name": "python-django",
            "processed_timestamp": "2021-07-18T03:09:03.013233Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}