{
    "TIMESTAMP": "2021-10-30T15:49:24.445875Z",
    "URL_requested": "https://badpackets.net/over-14500-pulse-secure-vpn-endpoints-vulnerable-to-cve-2019-11510/",
    "uvi_script_name": "./mirror-url-requests.py",
    "uvi_script_version": "0.0.3"
}