{
    "osv": {
        "package": {
            "name": "python-apt"
        },
        "published": "2020-01-23",
        "references": [
            {
                "type": "DSA",
                "url": "https://www.debian.org/security/2020/dsa-4609"
            }
        ]
    },
    "uvi": {
        "experimental": {
            "advisory_type": "DSA-4609-1",
            "other_identifiers": {
                "cve": [
                    "CVE-2019-15796",
                    "CVE-2019-15795"
                ]
            },
            "package_affected": [
                {
                    "distribution_affected": "stretch",
                    "fixed in": "1.4.1"
                },
                {
                    "distribution_affected": "buster",
                    "fixed in": "1.8.4.1"
                }
            ],
            "package_name": "python-apt",
            "processed_timestamp": "2021-07-18T03:09:19.749918Z",
            "uvi_script_name": "./www.debian.org-processing.py",
            "uvi_script_version": "0.0.5",
            "vulnerability_status": "yes"
        },
        "product_name": "Linux",
        "vendor_name": "Debian"
    }
}