{
    "error": "HTTPConnectionPool(host='alt.swiecki.net', port=80): Max retries exceeded with url: /linux_kernel/sys_open-kmem_cache_alloc-2.6.39-rc4.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7effc5b4a1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
}